### ISSUE TITLE
Now displays 72.png" loading="lazy">

### ISSUE THREAD

**Issue by robertandrews** [polishmatt/Short-Gmail-Labels#1] opened 2021-08-09 10:18 UTC
I'd say I've used this for years, it's great.
But now the label just seems to display `72.png" loading="lazy">`

<img width="225" alt="Screenshot 2021-08-09 at 11 18 21" src="https://user-images.githubusercontent.com/3158787/128691959-0a78f0bb-291e-4e7e-8b0b-da86e0d8e8bc.png">

**Comment by quicksite** [comment] 2021-08-12 00:38
Wow, robert, that's exactly what I came to post here!  Exact same for me. Have used this for years and Matthew's extension is such a godsend.  But sometime in the last 2+ weeks I too began experiencing this. At first I wasn't sure it was connected to this Extension, but after 2 support sessions with Google One, using screen sharing, we troubleshot and finally confirmed with certainly, this was happening only with Short Gmail Labels. When both uninstalling the extension, then reinstalling it, that exact string [   72.png" loading="lazy">   ] was replacing several leading characters in the Label Name. 

@polishmatt I don't know if you've abandoned this extension but it's been a lifesaver for me with ADHD removing all the un-useful clutter of Parent Folder / Sub-Label visual distractibility. If you see these 2 reports of the same problem, hope you may take a look under the hood re what might have suddenly corrupted what had been perfect & problem-free performance for years. I would gladly pay for this extension, and I've never understood why it doesn't have over a million users.  Thank you

<img width="340" alt="Short Gmail labels 4" src="https://user-images.githubusercontent.com/128756/129120984-c39a1da5-d7e5-4213-a65a-b5259825489f.png">

**Comment by polishmatt** [comment] 2021-08-12 02:58
Thanks for the report!

I've submitted a fix for review with Google. I don't know what to expect with that process but will close this out when that's complete.

In the meantime you could download the latest version from github and run it as an unpacked extension.

**Comment by quicksite** [comment] 2021-08-12 08:10
Thank you Matt. I'm not so smart in tech knowhow.
Unpacked. Does that mean the github download is compressed?  And it
extracts into a .crx file?  If so, I understand that.

**Comment by robertandrews** [comment] 2021-08-12 13:05
@polishmatt Thanks, it works for me!

@quicksite Download and unzip the code. Go to Chrome's Extensions page, click Load Unpacked and navigate to select the unzipped folder.

**Comment by polishmatt** [comment] 2021-08-20 19:33
Looks like Google has approved the update. You should be able to stop using the unpacked extension from github and go back to the normal one.

**Closed as completed by polishmatt** 2021-08-20 19:33 UTC

**Comment by quicksite** [comment] 2021-08-21 03:30
Fantastic Matt, thanks very much!  Short Labels Forever!
